---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: install npm
  become: true
  apt:
    name: npm
    state: present
    update_cache: yes

- name: install node js
  become: true
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    state: present
    global: yes

- name: create web directory
  become: true
  shell: mkdir ~/web

- name: copy index page to web
  copy:
    src: index.js
    dest: ~/web/index.js
    backup: yes

- name: start web server
  become: true
  shell: pm2 start ~/web/index.js -f

